### ISSUE TITLE
Define high level types in main module level to provide naming conventions

### ISSUE THREAD

**Issue by mustafaturan** [otobus/event_bus#46]
Current `EventBus` main module spec does not provide high-level type specs for the type safety. 

**TODO:**
- [x] Add public high-level types for each function to prevent misusage of functions.
- [x] Remove string type support on topic name registrations and deregistration
- [x] Allow event_shadow as tuple on `mark_as_completed/1` and `mark_as_skipped/1`
